kind: ConfigMap
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mtlsqm
  namespace: tools
spec:
  version: 9.2.2.0-r1
  license:
    accept: true
    license: L-RJON-BXUPZ2
    use: "Production"
  pki:
    keys:
    - name: default
      secret:
        secretName: qmcerts
        items:
          - tls.key
          - tls.crt
    trust:
    - name: app
      secret:
        secretName: mqtrustcerts
        items:
          - application.crt
  web:
    enabled: true
  queueManager:
    ini:
      - configMap:
          name: mtlsmqsc
          items:
            - example.ini
    mqsc:
      - configMap:
          name: mtlsmqsc
          items:
            - example.mqsc
